image: maven:3-eclipse-temurin-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "-B --errors --fail-at-end --show-version"

stages:
  - compile
  - test
  - verify
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}-maven-cache
  paths:
    - .m2/repository
  policy: pull-push

before_script:
  - mkdir -p .m2/repository

# ─── Pipeline scope ────────────────────────────────────────────────────────────
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" &&
        ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" ||
        $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")
      when: always
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never

# ─── Build & test ─────────────────────────────────────────────────
compile-job:
  stage: compile
  script:
    - mvn clean compile $MAVEN_CLI_OPTS
  artifacts:
    paths:
      - target/
    expire_in: 2 hours
    when: always

unit-test-job:
  stage: test
  script:
    - mvn test $MAVEN_CLI_OPTS

verify-job:
  stage: verify
  allow_failure: false
  script:
    - mvn verify $MAVEN_CLI_OPTS

publish-docs-pages:
  stage: deploy
  image: maven:3-eclipse-temurin-21
  needs: [verify-job]
  script:
    # Generate API docs
    - mvn -DskipTests=true javadoc:javadoc $MAVEN_CLI_OPTS
    # GitLab Pages serves whatever is in ./public
    - mv target/site/apidocs public
  pages:
    expire_in: never
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
      when: on_success