image: maven:3.9.9-eclipse-temurin-21

stages:          # List of stages for jobs, and their order of execution
  - compile
  - test
  - verify

compile-job:     # This job runs in the compile stage.
  stage: compile
  script:
    - mvn clean compile -B

unit-test-job:   # This job runs in the test stage.
  stage: test
  script:
    - mvn test -B

verify-job:      # This job runs in the verify stage.
  stage: verify
  script:
    - mvn verify -B