image: maven:latest

stages:
  - compile
  - test
  - verify

cache:
  paths:
    - .m2/repository
  key: ${CI_COMMIT_REF_SLUG}

before_script:
  - mkdir -p .m2/repository  # Ensure the directory exists

compile-job:
  stage: compile
  script:
    - mvn clean compile -B -Dmaven.repo.local=.m2/repository

unit-test-job:
  stage: test
  script:
    - mvn test -B -Dmaven.repo.local=.m2/repository

verify-job:
  stage: verify
  script:
    - mvn verify -B -Dmaven.repo.local=.m2/repository
