image: maven:3-eclipse-temurin-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "-B --errors --fail-at-end --show-version"

stages:
  - compile
  - test
  - verify

cache:
  key: ${CI_COMMIT_REF_SLUG}-maven-cache
  paths:
    - .m2/repository
  policy: pull-push

before_script:
  - mkdir -p .m2/repository  # Ensure the directory exists

# Global rules to apply to all jobs
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")
      when: always
    - when: never  # Skip all other cases

compile-job:
  stage: compile
  script:
    - mvn clean compile $MAVEN_CLI_OPTS
  artifacts:
    paths:
      - target/  # Save compiled artifacts for later stages
    expire_in: 2 hours
    when: always

unit-test-job:
  stage: test
  script:
    - mvn test $MAVEN_CLI_OPTS

verify-job:
  allow_failure: false
  stage: verify
  script:
    - mvn verify $MAVEN_CLI_OPTS