package edu.ntnu.idi.bidata.tiedy.frontend.util;

import edu.ntnu.idi.bidata.tiedy.backend.model.task.Task;
import edu.ntnu.idi.bidata.tiedy.frontend.controller.TaskDialogController;
import java.util.function.Consumer;
import javafx.scene.control.Alert;
import javafx.scene.control.Dialog;

/**
 * Utility class for generating JavaFX alerts with predefined configurations. This class simplifies
 * the creation of warning and error alerts in a JavaFX application.
 *
 * <p>The alerts generated by this class include a title and a content message. This avoids
 * repetitive code for creating alert dialogs.
 *
 * <p>This class is not meant to be instantiated, as it contains only static methods.
 *
 * @author Nick Heggø
 * @version 2025.03.28
 */
public class JavaFxFactory {
  private JavaFxFactory() {}

  /**
   * Generates a JavaFX information alert with a predefined title ("Info") and the provided content
   * message. This method is intended to streamline the creation of information alert dialogs in
   * JavaFX applications.
   *
   * @param title the title of the alert to be displayed
   * @param message the content message to be displayed in the alert dialog
   * @return an Alert object of type INFORMATION with the specified content message
   */
  public static Alert generateInfoAlert(String title, String message) {
    Alert alert = new Alert(Alert.AlertType.INFORMATION);
    alert.setTitle(title);
    alert.setContentText(message);
    return alert;
  }

  public static Alert generateInfoAlert(String message) {
    return generateInfoAlert("Info", message);
  }

  /**
   * Creates and returns a JavaFX warning alert with a predefined title ("Warning") and the provided
   * content message. This method is designed to simplify the generation of warning alert dialogs in
   * JavaFX applications.
   *
   * @param title the title of the alert to be displayed
   * @param message the content message to be displayed in the warning alert
   * @return an Alert object of type WARNING with the specified message as content
   */
  public static Alert generateWarningAlert(String title, String message) {
    Alert alert = new Alert(Alert.AlertType.WARNING);
    alert.setTitle(title);
    alert.setContentText(message);
    return alert;
  }

  public static Alert generateWarningAlert(String message) {
    return generateWarningAlert("Warning", message);
  }

  /**
   * Creates and returns a JavaFX error alert with a predefined title ("Error") and the provided
   * content message. This method is designed to simplify the creation of error alert dialogs in
   * JavaFX applications.
   *
   * @param title the title of the alert to be displayed
   * @param message the content message to be displayed in the error alert
   * @return an Alert object of type ERROR with the specified message as content
   */
  public static Alert generateErrorAlert(String title, String message) {
    Alert alert = new Alert(Alert.AlertType.ERROR);
    alert.setTitle(title);
    alert.setContentText(message);
    return alert;
  }

  public static Alert generateErrorAlert(String message) {
    return generateErrorAlert("Error", message);
  }

  public static Alert generateConfirmationAlert(String title, String message) {
    Alert alert = new Alert(Alert.AlertType.CONFIRMATION);
    alert.setTitle(title);
    alert.setContentText(message);
    return alert;
  }

  public static Alert generateConfirmationAlert(String message) {
    return generateConfirmationAlert("Confirmation", message);
  }

  /**
   * Generates a JavaFX information alert displaying the details of a provided task. The alert
   * includes the task's title, description, status, priority, and due date.
   *
   * @param task the Task object containing the details to be displayed; must not be null
   * @return an Alert object of type INFORMATION preconfigured with the task's details
   * @throws IllegalArgumentException if the task parameter is null
   */
  public static Alert generateTaskDialog(Task task) {
    var dialog = new Alert(Alert.AlertType.INFORMATION);
    dialog.setTitle("Task details");
    String template =
        """
        Description: %s
        Status: %s
        Priority: %s
        Due date: %s""";
    dialog.setHeaderText(task.getTitle());
    dialog.setContentText(
        template.formatted(
            task.getDescription(),
            task.getStatus().toString(),
            task.getPriority().toString(),
            task.getDeadline().toString()));
    return dialog;
  }

  public static Dialog<Task> createTaskDialog(Task task, Consumer<Task> onSaveCallback) {
    return TaskDialogController.createDialog(task, TaskDialogController.Mode.VIEW, onSaveCallback);
  }

  public static Dialog<Task> createNewTaskDialog(Consumer<Task> onSaveCallback) {
    return TaskDialogController.createDialog(
        null, TaskDialogController.Mode.CREATE, onSaveCallback);
  }

  public static Dialog<Task> editTaskDialog(Task task, Consumer<Task> onSaveCallback) {
    return TaskDialogController.createDialog(task, TaskDialogController.Mode.EDIT, onSaveCallback);
  }

  public static Dialog<Task> deleteTaskDialog(Task task, Consumer<Task> onSaveCallback) {
    return TaskDialogController.createDialog(
        task, TaskDialogController.Mode.DELETE, onSaveCallback);
  }
}
