package edu.ntnu.idi.bidata.tiedy.frontend.util;

import javafx.scene.control.Alert;

/**
 * Utility class for generating JavaFX alerts with predefined configurations. This class simplifies
 * the creation of warning and error alerts in a JavaFX application.
 *
 * <p>The alerts generated by this class include a title and a content message. This avoids
 * repetitive code for creating alert dialogs.
 *
 * <p>This class is not meant to be instantiated, as it contains only static methods.
 *
 * @author Nick Heggø
 * @version 2025.03.19
 */
public class JavaFxFactory {
  private JavaFxFactory() {}

  /**
   * Creates and returns a JavaFX warning alert with a predefined title ("Warning") and the provided
   * content message. This method is designed to simplify the generation of warning alert dialogs in
   * JavaFX applications.
   *
   * @param message the content message to be displayed in the warning alert
   * @return an Alert object of type WARNING with the specified message as content
   */
  public static Alert generateWarningAlert(String message) {
    Alert alert = new Alert(Alert.AlertType.WARNING);
    alert.setTitle("Warning");
    alert.setContentText(message);
    return alert;
  }

  /**
   * Creates and returns a JavaFX error alert with a predefined title ("Error") and the provided
   * content message. This method is designed to simplify the creation of error alert dialogs in
   * JavaFX applications.
   *
   * @param message the content message to be displayed in the error alert
   * @return an Alert object of type ERROR with the specified message as content
   */
  public static Alert generateErrorAlert(String message) {
    Alert alert = new Alert(Alert.AlertType.ERROR);
    alert.setTitle("Error");
    alert.setContentText(message);
    return alert;
  }
}
